[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv venv",
    "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "source venv/bin/activate && cd backend && python main.py" 