[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.10" 